version: '3.8'

services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - net


  bot:
    build: ..
    container_name: bot
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    environment:
      - TELEGRAM_APITOKEN
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal.:5432/${POSTGRES_DB}?sslmode=disable
      - SMTP_EMAIL
      - SMTP_PASSWORD
      - ADMIN_CHAT_ID
      - LOG_CHAT_ID
    depends_on:
      - postgres
    networks:
      - net
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok
    container_name: ngrok
    command: http --url=${NGROK_URL} bot:8080 
    environment:
      - NGROK_AUTHTOKEN
    depends_on:
      - bot
    networks:
      - net
    restart: unless-stopped
    
networks:
  net:
    driver: bridge